[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd scripts && python api.py"
healthcheckPath = "/health"
healthcheckTimeout = 100

[service]
internalPort = 8000
